### ISSUE TITLE
Add the data combination that Ian + Richard used

### ISSUE THREAD

**Issue by MatthieuSchaller** [SWIFTSIM/velociraptor-comparison-data#40]
for the GSMF and sizes. I don't have access to it...

**Comment by JBorrow** [comment]
We already have this https://github.com/SWIFTSIM/velociraptor-comparison-data/blob/master/data/GalaxyStellarMassFunction/conversion/convertVernon.py

**Comment by JBorrow** [comment]
https://github.com/SWIFTSIM/velociraptor-comparison-data/blob/master/data/GalaxyStellarMassGalaxySize/conversion/convertVernon.py

**Comment by MatthieuSchaller** [comment]
Ok... I'll add a "key calibration plots" section then with just the three main plots and the data we picked thus far.

**Comment by JBorrow** [comment]
Ah please wait on this. I have an idea for that :).

**Comment by MatthieuSchaller** [comment]
Sure. I don't need to be told twice not to do more work.

**Comment by JBorrow** [comment]
It also requires some core work in the VR library and just as I'm sure you'd never ask me to touch `scheduler.c` without good reason I won't ask you to touch `autoplotter/objects.py`

**Comment by MatthieuSchaller** [comment]
Only if I can write it in python 2
