### ISSUE TITLE
Stellar mass functions from TNG

### ISSUE THREAD

**Issue by calvin-sykes** [SWIFTSIM/velociraptor-comparison-data#76]
It isn't exactly observational data, but would the GSMF from Illustris (TNG) be of interest?
I currently have z=2 and z=5 mass functions for the TNG50 box but could get any combination of boxes/redshifts.

**Comment by JBorrow** [comment]
Sure, could definitely be useful. Feel free to add these, and any you think are useful. It would be helpful to have z=1, z=0.5, z=0 at the very least.

**Comment by calvin-sykes** [comment]
closed by #77
